settings = {
"winMafftPath" : "mafft/mafft-win/mafft.bat",
"linuxMafftPath" : "/usr/bin/mafft",
"refSeqId": "Suny_sequence",
"refSeqSequence": "GTGGTAAAATCTGCCTAAACGGGGAAACTCTCACTGAGACAATCCCGTGCTAAATCAGCAATAGCTGTAAATGCCTAACGACTACACGGTAGACAACTCTAAGAGTTGAAGGTATAGTCTAAACTGCATGGTGACATGCAGATATCGG",
"Suny_beginning" : "TAAAATCTGCCTAAACGG",
"Suny_beginning2" : "TCTGCCTAAACGG",
"sub2": "AACTTCAAATATCTTCGGAACTCA",
"sub2Strict": "CAGATATCGGAACTTCAAATATCTTCGGAACTCA",
# "exon": "TCCCTATCTCTCTAT",
"exon": "TGGTGACATGCAGATATCGG",
"exon_N_sub2" :(r"CAGATATCGGTCCCTATCTCTCTAT[A,C,C,G]{1,20}AACTTCAAATATCTTCGGAACTCA"),
"sunY_end":"CAGATATCGG",

}


def getSettings():
    return settings 